Src/Dft.DTRO.Admin/Models/DtroHistory/DtroHistoryProvisionResponse.cs
namespace Dft.DTRO.Admin.Models.DtroHistory;

public class DtroHistoryProvisionResponse
{
    public string ActionType { get; set; }

    public DateTime? Created { get; set; }

    public ExpandoObject Data { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string Reference { get; set; }

    public string SchemaVersion { get; set; }
}

Src/Dft.DTRO.Admin/Models/DtroHistory/DtroHistorySourceResponse.cs
namespace Dft.DTRO.Admin.Models.DtroHistory;
public class DtroHistorySourceResponse
{
    public string ActionType { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string Reference { get; set; }

    public string SchemaVersion { get; set; }

    public string Section { get; set; }

    public int TrafficAuthorityCreatorId { get; set; }

    public int TrafficAuthorityOwnerId { get; set; }

    public string TroName { get; set; }
}

Src/Dft.DTRO.Admin/Models/Metrics/FullMetric.cs
namespace Dft.DTRO.Admin.Models.Metrics;

public class FullMetricSummary
{
    [DataMember(Name = "forDate")]
    public string ForDate { get; set; }

    [DataMember(Name = "userName")]
    public string UserName { get; set; } = string.Empty;

    [DataMember(Name = "systemFailureCount")]
    public int SystemFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionFailureCount")]
    public int SubmissionFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionCount")]
    public int SubmissionCount { get; set; } = 0;

    [DataMember(Name = "deletionCount")]
    public int DeletionCount { get; set; } = 0;

    [DataMember(Name = "searchCount")]
    public int SearchCount { get; set; } = 0;

    [DataMember(Name = "eventCount")]
    public int EventCount { get; set; } = 0;
}

Src/Dft.DTRO.Admin/Models/Metrics/MetricRequest.cs
namespace Dft.DTRO.Admin.Models.Metrics;


[DataContract]
public class MetricRequest
{
    [DataMember(Name = "dtroUserId")]
    public Guid? DtroUserId { get; set; }

    [DataMember(Name = "dateFrom")]
    public DateTime DateFrom { get; set; }

    [DataMember(Name = "dateTo")]
    public DateTime DateTo { get; set; }

    [DataMember(Name = "userGroup")]
    public UserGroup UserGroup { get; set; }
}

Src/Dft.DTRO.Admin/Models/Metrics/MetricSummary.cs
namespace Dft.DTRO.Admin.Models.Metrics;

public class MetricSummary
{
    [DataMember(Name = "systemFailureCount")]
    public int SystemFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionFailureCount")]
    public int SubmissionFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionCount")]
    public int SubmissionCount { get; set; } = 0;

    [DataMember(Name = "deletionCount")]
    public int DeletionCount { get; set; } = 0;

    [DataMember(Name = "searchCount")]
    public int SearchCount { get; set; } = 0;

    [DataMember(Name = "eventCount")]
    public int EventCount { get; set; } = 0;
}

Src/Dft.DTRO.Admin/Models/Search/BoundingBox.cs
namespace Dft.DTRO.Admin.Models.Search;

public record struct BoundingBox(double westLongitude, double southLatitude, double eastLongitude, double northLatitude)
{
    public static readonly BoundingBox ForOsgb36Epsg27700 = new(-103976.3, -16703.87, 652897.98, 1199851.44);

    public static readonly BoundingBox ForWgs84Epsg4326 = new(-7.5600, 49.9600, 1.7800, 60.8400);
}

Src/Dft.DTRO.Admin/Models/Search/ComparisonOperator.cs
namespace Dft.DTRO.Admin.Models.Search;

[DataContract]
public enum ComparisonOperator
{
    [EnumMember(Value = "=")]
    Equal,

    [EnumMember(Value = ">")]
    GreaterThan,

    [EnumMember(Value = ">=")]
    GreaterThanOrEqual,

    [EnumMember(Value = "<")]
    LessThan,

    [EnumMember(Value = "<=")]
    LessThanOrEqual
}

Src/Dft.DTRO.Admin/Models/Search/DtroSearch.cs
namespace Dft.DTRO.Admin.Models.Search;

public class DtroSearch : PaginatedRequest
{
    [MinLength(1)]
    public IEnumerable<SearchQuery> Queries { get; set; }
}

Src/Dft.DTRO.Admin/Models/Search/Location.cs
namespace Dft.DTRO.Admin.Models.Search;

public class Location
{
    [Required]
    [RegularExpression(
        "^(?:osgb36Epsg27700|wgs84Epsg4326)$",
        ErrorMessage = "Value must be one of 'osgb36Epsg27700' and 'wgs84Epsg4326'.")]
    public string Crs { get; set; }

    [Required]
    public BoundingBox Bbox { get; set; }
}

Src/Dft.DTRO.Admin/Models/Search/PaginatedRequest.cs
namespace Dft.DTRO.Admin.Models.Search;

public class PaginatedRequest
{
    [Range(1, int.MaxValue)]
    [Required]
    public int Page { get; set; }

    [Range(1, 50)]
    [Required]
    public int PageSize { get; set; }
}

Src/Dft.DTRO.Admin/Pages/DtroDropEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroDropEditModel : PageModel
{
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;
    public DtroDropEditModel(IDtroService dtroService, IConfiguration configuration, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public string Id { get; set; }

    public async Task<IActionResult> OnPostAsync(IFormFile file, bool isEdit, string id)
    {
        try
        {
            if (isEdit)
            {
                await _dtroService.UpdateDtroAsync(Guid.Parse(id), file);
            }
            else
            {
                await _dtroService.CreateDtroAsync(file);
            }

            return RedirectToPage("Search");
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroEditModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;
    [BindProperty(SupportsGet = true)]
    public DtroUserSearch DtroUserSearch { get; set; } = new DtroUserSearch();

    [BindProperty(SupportsGet = true)]
    public string Id { get; set; }

    public DtroEditModel(IDtroService dtroService, IDtroUserService traService, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _dtroUserService = traService;
        _errHandlingService = errHandlingService;
    }

    public async Task OnGetAsync()
    {
        DtroUserSearch.AlwaysButtonHidden = true;
        DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();
        DtroUserSearch.DtroUsers.RemoveAll(x => x.UserGroup != UserGroup.Tra);
    }


    public async Task<IActionResult> OnPostAsync(Guid id)
    {
        try
        {
            if (TempData.TryGetValue("DtroUserSelect", out object dtroUserSelect))
            {
                DtroUserSearch.DtroUserIdSelect = (Guid)dtroUserSelect;
            }

            if (DtroUserSearch.DtroUserIdSelect != null)
            {
                await _dtroService.ReassignDtroAsync(id, DtroUserSearch.DtroUserIdSelect.Value);

            }

            return RedirectToPage("Search");
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroHistory.cshtml.cs
namespace Dft.DTRO.Admin.Pages;

public class DtroHistoryModel : PageModel
{
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;

    [BindProperty(SupportsGet = true)]
    public Guid Id { get; set; }

    [BindProperty(SupportsGet = true)]
    public List<DtroHistoryProvisionResponse> ProvisionHistory { get; set; }

    [BindProperty(SupportsGet = true)]
    public List<DtroHistorySourceResponse> SourceHistory { get; set; }


    public DtroHistoryModel(IDtroService dtroService, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _errHandlingService = errHandlingService;
    }

    public async Task<IActionResult> OnGetAsync()
    {


        try
        {
            SourceHistory = await _dtroService.DtroSourceHistory(Id);
            ProvisionHistory = await _dtroService.DtroProvisionHistory(Id);
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

}

Src/Dft.DTRO.Admin/Pages/DtroUserEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroUserEditModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly ISystemConfigService _systemConfigService;
    private readonly IErrHandlingService _errHandlingService;

    public DtroUserEditModel(IDtroUserService dtroUserService, ISystemConfigService systemConfigService, IErrHandlingService errHandlingService)
    {
        _systemConfigService = systemConfigService;
        _dtroUserService = dtroUserService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public Guid? DtroUserId { get; set; }

    [BindProperty(SupportsGet = true)]
    public bool IsEdit { get; set; }

    [BindProperty(SupportsGet = true)]
    public bool IsTestSystem { get; set; }

    [BindProperty]
    public DtroUser DtroUser { get; set; }

    [BindProperty(SupportsGet = true)]
    public string Search { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        try
        {
            var systemConfig = await _systemConfigService.GetSystemConfig();
            IsTestSystem = systemConfig.IsTest;

            if (IsEdit)
            {
                DtroUser = await _dtroUserService.GetDtroUserAsync(DtroUserId.Value);
            }
            else
            {
                DtroUser = new DtroUser();
            }
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public async Task<IActionResult> OnPostAsync()
    {
        try
        {
            var action = Request.Form["action"];
            if (action == "Cancel")
            {
                return RedirectToPage("DtroUserList", new { search = Search });
            }

            if (IsEdit)
            {
                DtroUser.Id = DtroUserId.Value;
                await _dtroUserService.UpdateDtroUserAsync(DtroUser);
            }
            else
            {
                await _dtroUserService.CreateDtroUserAsync(DtroUser);
                Search = DtroUser.Name;
            }

            return RedirectToPage("DtroUserList", new { search = Search });
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroUserList.cshtml.cs
namespace Dft.DTRO.Admin.Pages;

public class DtroUserListModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly IErrHandlingService _errHandlingService;

    public DtroUserListModel(IDtroUserService dtroUserService, IErrHandlingService errHandlingService)
    {
        _dtroUserService = dtroUserService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public DtroUserSearch DtroUserSearch { get; set; } = new DtroUserSearch();
    public List<DtroUser> FilteredDtroUsers { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        try
        {
            DtroUserSearch.AlwaysButtonEnabled = true;
            if (DtroUserSearch.Search != "" && DtroUserSearch.PreviousSearch == "")
            {
                DtroUserSearch.PreviousSearch = DtroUserSearch.Search;
            }

            DtroUserSearch.UpdateButtonText = "List";
            DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();

            if (DtroUserSearch.DtroUserIdSelect != null && DtroUserSearch.DtroUserIdSelect != Guid.Empty)
            {
                FilteredDtroUsers = DtroUserSearch.DtroUsers.Where(s => s.Id == DtroUserSearch.DtroUserIdSelect).ToList();
            }
            else
            {
                if (!string.IsNullOrWhiteSpace(DtroUserSearch?.Search))
                {
                    FilteredDtroUsers = await _dtroUserService.SearchDtroUsersAsync(DtroUserSearch.Search);
                }
                else
                {
                    FilteredDtroUsers = new List<DtroUser>();
                }
            }
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public async Task<IActionResult> OnPostUpdate()
    {
        try
        {
            OnGetAsync().Wait();
            var action = Request.Form["action"];

            if (Guid.TryParse(action, out Guid dtroUserId))
            {
                if (dtroUserId != Guid.Empty)
                {
                    DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();
                    var dtroUser = DtroUserSearch.DtroUsers.Find(s => s.Id == dtroUserId);
                    if (dtroUser == null) return NotFound();

                    //To 
                    await _dtroUserService.DeactivateDtroUserAsync(dtroUserId);
                    await _dtroUserService.ActivateDtroUserAsync(dtroUserId);
                }
                DtroUserSearch.Search = DtroUserSearch.PreviousSearch;
                DtroUserSearch.DtroUserIdSelect = DtroUserSearch.PreviousDtroUserIdSelect;
            }
            else
            {
                if (DtroUserSearch.PreviousSearch != "" && DtroUserSearch.Search == null)
                {
                    DtroUserSearch.Search = DtroUserSearch.PreviousSearch;
                }
                else
                {
                    DtroUserSearch.PreviousSearch = DtroUserSearch.Search;
                }

                DtroUserSearch.PreviousDtroUserIdSelect = DtroUserSearch.DtroUserIdSelect;
            }
            return RedirectToPage(new { DtroUserSearch.Search, DtroUserSearch.DtroUserIdSelect, DtroUserSearch.PreviousDtroUserIdSelect, DtroUserSearch.PreviousSearch });

        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public IActionResult OnGetRefresh()
    {
        return RedirectToPage(new { DtroUserSearch.DtroUserIdSelect });
    }

    public string FormatListToSingle(IEnumerable<string> items)
    {
        var formattedItems = new List<string>();
        foreach (var item in items)
        {
            string formattedItem = Regex.Replace(item, "(?<!^)([A-Z])", " $1");
            formattedItem = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(formattedItem.ToLower());
            formattedItems.Add(formattedItem);
        }
        return string.Join(", ", formattedItems);
    }
}

Src/Dft.DTRO.Admin/Pages/Error.cshtml.cs
using Dft.DTRO.Admin.Models.Errors;
using Dft.DTRO.Admin.Models.Views;

namespace Dft.DTRO.Admin.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ErrorView ErrorView { get; set; }

    public void OnGet()
    {


        var errorView = HttpContext.Session.GetString("errorView");
        if (!string.IsNullOrEmpty(errorView))
        {
            ErrorView = JsonSerializer.Deserialize<ErrorView>(errorView);

            if (ErrorView == null)
            {
                ErrorView = new ErrorView
                {
                    ErrorType = "UI - Unable to process error details"
                };
            }

            if (HttpContext.Session.GetString("dtroValidationException") != null)
            {
                ErrorView.DtroValidationException = JsonSerializer.Deserialize<DtroValidationExceptionResponse>((string)HttpContext.Session.GetString("dtroValidationException"));

                if (ErrorView.DtroValidationException.RequestComparedToSchema != null)
                {
                    var unPackedList = unPackList(ErrorView.DtroValidationException.RequestComparedToSchema);
                    ErrorView.DtroValidationException.RequestComparedToSchema = unPackedList.Distinct(new DtroJsonValidationErrorResponseComparer()).ToList();
                }
            }

        }
        else
        {
            ErrorView = new ErrorView
            {
                ErrorType = "UI - No error details provided"
            };
        }
    }

    private List<DtroJsonValidationErrorResponse> unPackList(List<DtroJsonValidationErrorResponse> list)
    {
        var ret = new List<DtroJsonValidationErrorResponse>();

        foreach (var item in list)
        {
            ret.Add(item);
            if (item.ChildErrors != null && item.ChildErrors.Count > 0)
            {
                var kids = unPackList((List<DtroJsonValidationErrorResponse>)item.ChildErrors);
                ret.AddRange(kids);
            }
            item.ChildErrors?.Clear();
        }

        return ret.Distinct(new DtroJsonValidationErrorResponseComparer()).ToList();
    }
}

public class DtroJsonValidationErrorResponseComparer : IEqualityComparer<DtroJsonValidationErrorResponse>
{
    public bool Equals(DtroJsonValidationErrorResponse x, DtroJsonValidationErrorResponse y)
    {
        if (x == null || y == null)
            return false;

        return x.Message.Trim() == y.Message.Trim() &&
               x.LineNumber == y.LineNumber &&
               x.LinePosition == y.LinePosition &&
               x.Path == y.Path;
    }

    public int GetHashCode(DtroJsonValidationErrorResponse obj)
    {
        return HashCode.Combine(obj.Message, obj.LineNumber, obj.LinePosition, obj.Path);
    }
}

Src/Dft.DTRO.Admin/Pages/DtroUserList.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model DtroUserListModel

<h2>Users <a class="btn btn-primary" asp-page="DtroUserEdit" asp-route-IsEdit="false">+</a></h2>

<form id="searchSection" method="post" asp-page-handler="Update" style=" margin-top: 30px;margin-right: 20px;margin-bottom: 20px;">
    <div>
        @await Html.PartialAsync("_TraSearchPartial", Model.DtroUserSearch)
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>App-Id</th>
                <th>Group</th>
                <th>TRA Id</th>
                <th>Prefix</th>
                <th>Name</th>
                <th>Active</th>
                <th>Admin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var dtroUser in Model.FilteredDtroUsers)
            {
                <tr>
                    <td>@(dtroUser.AppId == Guid.Empty ? "(Not Set)" : dtroUser.AppId.ToString())</td>
                    <td>@dtroUser.UserGroup.ToString()</td>
                    <td>@dtroUser.TraId</td>
                    <td>@dtroUser.Prefix</td>
                    <td>@dtroUser.Name</td>
                    <td>
                        @if (dtroUser.AppId != Guid.Empty)
                        {
                            <img src="@Url.Content("~/images/tick.png")" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/images/cross.png")" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        @if (dtroUser.UserGroup == UserGroup.Admin)
                        {
                            <img src="@Url.Content("~/images/tick.png")" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/images/cross.png")" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        <a class="btn btn-info" asp-page="DtroUserEdit" asp-route-IsEdit="true" asp-route-search="@Model.DtroUserSearch.PreviousSearch" asp-route-dtroUserId="@dtroUser.Id">Edit</a>
                       
                        
                     @*    <button type="submit" 
                            name="action" 
                            value= "@dtroUser.TraId"
                            class="btn btn-@(dtroUser.IsActive ? "warning" : "success")" 
                            style="min-width: 100px;">
                                @(dtroUser.IsActive ? "Disable" : "Enable")
                            </button> *@
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

Src/Dft.DTRO.Admin/Pages/Metrics.cshtml
@page
@model MetricsModel
@{
    ViewData["Title"] = "Metrics";
}

<div class="text-center" style="margin-top: 50px; margin-bottom: 50px">
    <h1 class="display-4">Metrics</h1>
</div>

<form id="searchSection" method="post" asp-page-handler="Update" style="display: flex;">
    <div>
        <!-- UserGroup Options -->
        <div class="options-container">
            <label>
                <input type="radio" name="UserGroup" value="Tra" checked="@((Model.UserGroup == "Tra"))" /> Publisher
            </label>
            <label>
                <input type="radio" name="UserGroup" value="Consumer" checked="@((Model.UserGroup == "Consumer"))" /> Consumer
            </label>
            <label>
                <input type="radio" name="UserGroup" value="Admin" checked="@((Model.UserGroup == "Admin"))" /> Admin
            </label>
        </div>

        <!-- Period Options -->
        <div class="options-container" style="color: grey">
            <label>
                <input type="radio" name="PeriodOption" value="days" checked="@((Model.PeriodOption == "days"))" /> Days
            </label>
            <label>
                <input type="radio" name="PeriodOption" value="weeks" checked="@((Model.PeriodOption == "weeks"))" /> Weeks
            </label>
            <label>
                <input type="radio" name="PeriodOption" value="months" checked="@((Model.PeriodOption == "months"))" /> Months
            </label>

            <select id="numberSelect" name="NumberSelect" asp-for="NumberSelect">
                @for (int i = 1; i <= 7; i++)
                {
                    <option value="@i" selected="@((Model.NumberSelect == i))">@i</option>
                }
            </select>
        </div>

        @await Html.PartialAsync("_TraSearchPartial", Model.DtroUserSearch)
    </div>

    <div id="pieChart" style="display: flex;">
        <div id="metrics" style="color: grey; padding-left: 10px; flex: 1; position: relative;">
            <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
                <div style="position: relative; width: 70vh; height: 50vh;">
                    <canvas id="metricSummaryChart" style="width: 100%; height: 100%;"></canvas>
                    <!-- Button Container -->
                    <div style="display: flex; justify-content: flex-end; margin-top: 20px;">
                        <button type="submit" name="exportCsv" value="true" class="btn btn-primary">
                            Export
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const periodOptions = document.querySelectorAll('input[name="PeriodOption"]');

            const updateButton = document.getElementById('updateButton');
            const userGroupOptions = document.querySelectorAll('input[name="UserGroup"]');
            const numberSelect = document.getElementById('numberSelect');
            const form = document.getElementById('searchSection');
            const selectedNumberValue = '@Model.NumberSelect'; // Use Razor to get the selected value

            // Function to update numberSelect options based on selected periodOption
            function updateNumberSelectOptions() {
                let max = 7;
                const selectedPeriod = document.querySelector('input[name="PeriodOption"]:checked').value;

                switch (selectedPeriod) {
                    case 'days':
                        max = 7;
                        break;
                    case 'weeks':
                        max = 4;
                        break;
                    case 'months':
                        max = 6;
                        break;
                }

                numberSelect.innerHTML = '';

                for (let i = 1; i <= max; i++) {
                    const option = document.createElement('option');
                    option.value = i;
                    option.textContent = i;
                    if (i == selectedNumberValue) { // Preserve the selected value
                        option.selected = true;
                    }
                    numberSelect.appendChild(option);
                }
            }

            // Function to enable and trigger the update button
            function triggerUpdateButton() {
                updateButton.disabled = false; // Enable the button
                updateButton.click();          // Trigger the button click
            }

            // Event listeners for UserGroup and PeriodOption changes to submit form
            userGroupOptions.forEach(option => {
                option.addEventListener('change', function () {

                    const traSearch = document.getElementById('traSearch');
                    if (traSearch) {
                        traSearch.focus();
                    }

                    triggerUpdateButton();  // Automatically trigger button click
                });
            });

            periodOptions.forEach(option => {
                option.addEventListener('change', function () {
                    updateNumberSelectOptions();
                    triggerUpdateButton();  // Automatically trigger button click
                });
            });

            // Event listener for numberSelect changes
            numberSelect.addEventListener('change', function () {
                triggerUpdateButton();  // Automatically trigger button click
            });

            // Initialize the options on page load
            updateNumberSelectOptions();

            // Update chart based on selected UserGroup
            function updateChart() {
                const userGroup = document.querySelector('input[name="UserGroup"]:checked').value;
                let labels = [];
                let data = [];

                // Update labels and data based on UserGroup
                if (userGroup === 'Admin') {
                    labels = ['Submission','Rejected','Deletion', 'Search', 'Event', 'Fault'];
                    data = [
                                @Model.Metrics.SubmissionCount,
                                @Model.Metrics.SubmissionFailureCount,
                                @Model.Metrics.DeletionCount,
                                @Model.Metrics.SearchCount,
                                @Model.Metrics.EventCount,
                                @Model.Metrics.SystemFailureCount
                            ];
                } else if (userGroup === 'Tra') {
                    labels = ['Submission', 'Rejected', 'Deletion', 'Fault'];
                    data = [
                                @Model.Metrics.SubmissionCount,
                                @Model.Metrics.SubmissionFailureCount,
                                @Model.Metrics.DeletionCount,
                                @Model.Metrics.SystemFailureCount
                           ];
                } else if (userGroup === 'Consumer') {
                    labels = ['Search', 'Event', 'Fault'];
                    data = [
                                @Model.Metrics.SearchCount,
                                @Model.Metrics.EventCount,
                                @Model.Metrics.SystemFailureCount
                           ];
                }

                // Destroy existing chart instance if exists
                if (window.metricChart) {
                    window.metricChart.destroy();
                }

                // Define color variables
                const pastelRed = 'rgba(255, 99, 132, 0.5)';
                const pastelOrange = 'rgba(255, 159, 64, 0.5)';
                const pastelGreen = 'rgb(144, 238, 144, 0.5)';
                const pastelDarkBlue = 'rgba(54, 162, 235, 0.5)';
                const pastelBlue = 'rgba(153, 102, 255, 0.5)';
                const pastelLightBlue = 'rgba(201, 203, 207, 0.5)';

                const borderRed = 'rgba(255, 99, 132, 1)';
                const borderOrange = 'rgba(255, 159, 64, 1)';
                const borderGreen = 'rgba(75, 192, 192, 1)';
                const borderDarkBlue = 'rgba(54, 162, 235, 1)';
                const borderBlue = 'rgba(153, 102, 255, 1)';
                const borderLightBlue = 'rgba(201, 203, 207, 1)';

                // Create a new chart
                const ctx = document.getElementById('metricSummaryChart').getContext('2d');
                window.metricChart = new Chart(ctx, {
                    type: 'bar', // You can change to 'pie', 'line', etc.
                    data: {
                        labels: labels,
                        datasets: [{
                            label: 'Metrics Summary',
                            data: data,
                            backgroundColor: [
                                pastelGreen,
                                pastelOrange,
                                pastelDarkBlue,
                                pastelBlue,
                                pastelLightBlue,
                                pastelRed
                            ],
                            borderColor: [
                                borderGreen,
                                borderOrange,
                                borderDarkBlue,
                                borderBlue,
                                borderLightBlue,
                                borderRed
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        plugins: {
                            legend: {
                                display: false
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1, // Ensures that the ticks are whole numbers
                                    callback: function (value) {
                                        return Number.isInteger(value) ? value : ''; // Display only whole numbers
                                    }
                                }
                            }
                        }
                    }
                });
            }

            // Initialize the chart on page load
            updateChart();

           
        });
    </script>

}